modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="patchouliguieditor" #mandatory
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Patchouli GUI Editor" #mandatory
logoFile="patchouliGuiEditor.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional

description='''
An unofficial addon mod to patchouli to edit the book in game skipping the anoying json files
'''
[[dependencies.patchouliguieditor]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.patchouliguieditor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.patchouliguieditor]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.19.2-76,)"
    ordering="NONE"
    side="BOTH"